# Generated by Django 2.1.7 on 2019-02-26 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_group_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('icon', models.ImageField(upload_to='media/icon/element/')),
                ('name', models.CharField(max_length=64)),
                ('date', models.DateField()),
                ('moderator_checked', models.NullBooleanField()),
            ],
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(upload_to='media/icon/group/'),
        ),
        migrations.AddField(
            model_name='element',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element+', to='api.Group'),
        ),
    ]
