# Generated by Django 2.1.7 on 2019-02-27 13:15

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190227_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='date',
            field=models.DateField(verbose_name='дата'),
        ),
        migrations.AlterField(
            model_name='element',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='element',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='api.Group', verbose_name='группа'),
        ),
        migrations.AlterField(
            model_name='element',
            name='icon',
            field=models.ImageField(upload_to='static/icon/element/', verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.NullBooleanField(verbose_name='проверен модератором'),
        ),
        migrations.AlterField(
            model_name='element',
            name='name',
            field=models.CharField(max_length=64, verbose_name='назваине'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='описание'),
        ),
        migrations.AlterField(
            model_name='group',
            name='icon',
            field=models.ImageField(upload_to='static/icon/group/', validators=[api.models.validator_icon], verbose_name='иконка'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=64, verbose_name='назваине'),
        ),
    ]
