# Generated by Django 2.1.7 on 2019-02-26 18:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190226_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_group+', to='api.Group'),
        ),
    ]
