# Generated by Django 2.1.7 on 2019-02-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190226_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='element',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
