# Generated by Django 2.1.7 on 2019-02-26 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190226_1856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='api.Group'),
        ),
        migrations.AlterField(
            model_name='group',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rel_group', to='api.Group'),
        ),
    ]
