# Generated by Django 2.1.7 on 2019-02-27 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190226_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.NullBooleanField(default=None),
        ),
    ]
