# Generated by Django 2.1.7 on 2019-02-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190227_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='icon',
            field=models.ImageField(upload_to='static/icon/element/'),
        ),
    ]
