# Generated by Django 2.1.7 on 2019-02-27 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20190227_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.NullBooleanField(default=django.db.models.deletion.SET_NULL),
        ),
    ]
