# Generated by Django 2.1.7 on 2019-02-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_auto_20190227_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.NullBooleanField(choices=[(None, ''), (True, 'Yes'), (False, 'No')], default=None),
        ),
    ]
