# Generated by Django 2.1.7 on 2019-02-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190227_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='moderator_checked',
            field=models.NullBooleanField(),
        ),
    ]
